services:
  postgres:
    image: postgres:latest
    container_name: weather_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'

  adminer:
    image: adminer:latest
    container_name: weather_adminer
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      ADMINER_PLUGINS: 'tables-filter tinymce edit-calendar enum-option'
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: ${POSTGRES_HOST}
    ports:
      - '8000:8080'
